### ISSUE TITLE
Error: More than one instance of bitcore-lib found

### ISSUE THREAD

**Issue by bethnull** [bitpay/i-made-this#15]
Hi there!

Running bitcored throws the following error:
`Error: More than one instance of bitcore-lib found. Please make sure to require bitcore-lib and check that submodules do not also include their own bitcore-lib dependency.`

It seems to be related with the fact that only one copy of bitcore-lib can be used/required by the whole app including the used modules, however the service requires it. 

After digging for a while, it seems that others are having issues with the same error in other projects, but a clear solution is'nt given. [bitcore#1188](https://github.com/bitpay/bitcore/issues/1188), [bitcore-lib#21](https://github.com/bitpay/bitcore-lib/issues/21), etc.

I must say that I've checked all the versions of bitcore-lib everywhere it's used, starting from a clean node installation, and all the versions installed are 0.13.19. But I think that it has nothing to do with the library version, as in the module is only checked that a variable is defined, actually: global._bitcore in line 15, checked if it's defined in line 8 of index.js. 

Quick and dirty fix: set it to undefined before var bitcore = require('bitcore-lib'); in index.js of the stampingservice, fooling bitcore.versionGuard in index.js of bitcore-lib. However I think it's not the way to go.

And what's more strange to me, has it worked before?

Regards, beth.

**Comment by braydonf** [comment]
You'll likely run into other issues by ignoring the assertion that is made. For example regtest that is enabled/disabled as a part of testnet, there are other cases as well.

When developing, symlinking bitcore-lib in both projects will most of the time resolve the issue:
- /home/user/projects/myservice/node_modules/bitcore-lib -> /home/user/projects/bitcore-lib
- /home/user/projects/bitcore-node/node_modules/bitcore-lib -> /home/user/projects/bitcore-lib

Alternatively, you can make bitcore-node and bitcore-lib both a dependency of the project, and setting up the symlinks is only necessary if you're developing and making changes to bitcore-lib as well.

**Comment by bethnull** [comment]
I understood.

Symlinking fixes the issue, however making both bitcore-node and bitcore-lib a dependency of a service don't.

Thanks for your support.

Kind regards, beth.
